//CUSTOMER API
POST http://localhost:3000/customer/new
content-type: application/json

{
    "name":"Momina Amer",
    "email":"momina@gmail.com",
    "password":"12345678",
    "address":"Pluto"
}

###

GET http://localhost:3000/customer/verify
Content-Type: application/json

{
    "email":"rohan@yahoo.com",
    "password":"12345678"
}

###


//SELLER API
POST http://localhost:3000/seller/new
content-type: application/json

{
    "name":"Vafa Batool",
    "email":"vafa@gmail.com",
    "password":"12345678",
    "cnic":"3520212345678",
    "cnic_image":"vafabatool.jpg",
    "location":"Baluchistan",
    "sec_questions":{"What is the name of your cat?":"Junaid","What is the name of your best friend?":"Junaid"}
}


###

GET http://localhost:3000/seller/verify
Content-Type: application/json

{
    "email":"vafa@gmail.com",
    "password":"12345678"
}

###

//ADMIN API
POST http://localhost:3000/admin/new
content-type: application/json

{
    "name":"Muhammad Rohan Hussain",
    "email":"rohan@yahoo.com",
    "password":"12345678"
}

###

GET http://localhost:3000/admin/verify
Content-Type: application/json

{
    "email":"rohan@yahoo.com",
    "password":"12345678"
}

###

GET http://localhost:3000/admin/all/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ik11aGFtbWFkIFJvaGFuIEh1c3NhaW4iLCJ0eXBlT2ZVc2VyIjoiYWRtaW4iLCJpYXQiOjE2MTY4NDE4MTZ9.HJvh_8caLMReaDmJFCEklgtP9u86usbNIZ4FxOrIawk


###
GET http://localhost:3000/admin/all/sellers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ik11aGFtbWFkIFJvaGFuIEh1c3NhaW4iLCJ0eXBlT2ZVc2VyIjoiYWRtaW4iLCJpYXQiOjE2MTY4NDE4MTZ9.HJvh_8caLMReaDmJFCEklgtP9u86usbNIZ4FxOrIawk

###
PATCH http://localhost:3000/admin/all/customers/block
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ik11aGFtbWFkIFJvaGFuIEh1c3NhaW4iLCJ0eXBlT2ZVc2VyIjoiYWRtaW4iLCJpYXQiOjE2MTY4NDE4MTZ9.HJvh_8caLMReaDmJFCEklgtP9u86usbNIZ4FxOrIawk
content-type: application/json

{
    "id":18
}
###

//GENERAL API
GET http://localhost:3000/images/vafabatool.jpg

//admin token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ik11aGFtbWFkIFJvaGFuIEh1c3NhaW4iLCJ0eXBlT2ZVc2VyIjoiYWRtaW4iLCJpYXQiOjE2MTY4NDE4MTZ9.HJvh_8caLMReaDmJFCEklgtP9u86usbNIZ4FxOrIawk

//customer token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsIm5hbWUiOiJNdWhhbW1hZCBSb2hhbiBIdXNzYWluIiwidHlwZU9mVXNlciI6ImN1c3RvbWVyIiwiaWF0IjoxNjE2ODQwMzY5fQ.0ORPPISR2pib-wEx2vLVC9-9zQYfbC0A6SI-P6w2l9c

//seller token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IlZhZmEgQmF0b29sIiwidHlwZU9mVXNlciI6InNlbGxlciIsImlhdCI6MTYxNjg0NDE3N30.xYaUcX7dmdqY5co2tMbVA_9jh0M1fVBB-AX0Aam5G7Y